export const LightTheme = {
	colors: {
		primary: '#8BAA36',
		primarySoft: '#EBF3D4',
		footerBG: '#22252A',
		bgModal: '#FAFAFA',
		bgBurger: 'rgb(235,243,212)',
		fontColor: '#fafafa',
		fontColorDark: '#3e4462',
		fontColorPassive: '#E0E0E0',
		titleColor: '#001833',
		fontColorNavigation: '#23262a',
		fontHero: '#22252A',
		followUsColor: '#8BAA36',
		followUsColorHover: '#FFFFFF',
		followUsBG: 'transparent',
		followUsBGHover: '#8BAA36',
		buttonLightBG: '#fafafa',
		buttonLightBGHover: '#22252A',
		buttonDarkBG: '#22252A',
		buttonPrimaryBG: '#8BAA36',
		textButtonPrimaryHover: '#22252A',

		btnLogOutBg: '#8BAA36',
		btnLogOutText: '#FAFAFA',
		btnLogOutHoverBG: '#22252A',
		btnCancelBg: '#D9D9D9',
		btnCancelText: '#23262A',
		btnCancelHoverBG: '#ECECEC',

		recipeListBackground: '#EBF3D4',
		recipeHero: '#22252A',
		recipeColor: '#3E4462',
		
		placeHolderInput: '#23262A',
		bgTitleCard: '#FFFFFF',
		bgMoreBtn: '#8BAA36',
		bgMoreBtnHover: '#1E1F28',
		bgBtnTransparent: 'transparent',
		fontColorBtnDark: '#22252A',
		fontColorBtnDarkHover: '#FAFAFA',
		followUsAddPacipesHover: '#22252A',
		colorTextTeam: '#22252A',

		darkBG: '#2a2c36',
		lightBG: '#FAFAFA',
		BGCintoButton: '#FFFFF',
		borderColorLight: '#f0f0f0',
		textSecondary: '#7E7E7E',
		addRecipeFormPlaceholder: 'rgba(0, 0, 0, 0.5)',
		addRecipeFormFieldsBackground: '#d9d9d9',
		addRecipeFormFieldsBorder: 'none',
		colorInput: '#000000',

		placeHolderColor: '#000000',
		borderColor: '#23262A',
		bgColorListSelectIngredient: '#FAFAFA',

		addRecipeFormFieldsTextColor: '#23262a',
		addRecipeFormFieldsDropdownBackground: '#ffffff',
		addRecipeFormFieldsDropdownButtonIcon: '#8BAA36',
		addRecipeDropDownBg: '#FFFFFF',

		addRecipeFormFieldsDropdownListPosition: 'rgba(0, 0, 0, 0.5)',
		addRecipeFormFieldsDropdownListHover: '#8BAA36',
		addRecipeFormFieldsDeleteButton: '#333333',
		addRecipeFormFieldsDelBtnHover: '#000000',
		addRecipeFormCounterButtons: 'rgba(51, 51, 51, 0.3)',
		colorCounter: '#333333',
		textShadow: 'none',
		fontColorNameUser: '#22252A',

		followUsHoverAddRecipePage: '#000000',
		addRecipeFormCounterButtonsHover: '#8baa36',
		searchFormBGbyTitle: '#3e4462',

		bgTrashIcon: '#EBF3D4',
		strokeTrashIcon: '#22252A',

		bgFavoriteItem: '#FFFFFF',
		colorFavoriteTitle: '#3E4462',
		textFavoriteRecipe: '#23262A',

		textNoResultsColor: '#000000',

		recipeItemBackgroundColor: '#ffffff',
		recipeTextColor: '#23262a',
		myRecipesTextColor: 'rgba(250, 250, 250, 0.6)',
		deleteIconStroke: '#fafafa',
	},
	media: {
		tablet: '(min-width: 768px)',
		desktop: '(min-width: 1440px)',
	},
};

export const DarkTheme = {
	colors: {
		primary: '#8BAA36',
		primarySoft: '#EBF3D4',
		footerBG: '#8BAA36',
		bgModal: '#2A2C36',
		bgBurger: '#2A2C36',
		fontColor: '#fafafa',
		fontColorDark: '#fafafa',
		fontColorPassive: '#E0E0E0',
		titleColor: '#FAFAFA',
		fontColorNavigation: '#808080',
		fontHero: '#FAFAFA',
		followUsColor: '#FFFFFF',
		followUsColorHover: '#1E1F28',
		followUsBG: '#8BAA36',
		foffowUsBGHover: 'transparent',
		buttonLightBG: '#fafafa',
		buttonLightBGHover: '#22252A',
		buttonDarkBG: '#8BAA36',
		buttonPrimaryBG: '#1E1F28',
		textButtonPrimaryHover: '#8BAA36',

		btnLogOutBg: '#8BAA36',
		btnLogOutText: '#FAFAFA',
		btnLogOutHoverBG: '#22252A',
		btnCancelBg: '#D9D9D9',
		btnCancelText: '#23262A',
		btnCancelHoverBG: '#ECECEC',

		recipeListBackground: '#2A2C36',
		recipeColor: '#FAFAFA',

		placeHolderInput: '#FAFAFA',
		bgTitleCard: '#2A2C36',
		bgMoreBtn: '#8BAA36',
		bgMoreBtnHover: '#8BAA36',
		bgBtnTransparent: 'transparent',
		fontColorBtnDark: '#FAFAFA',
		fontColorBtnDarkHover: '#FAFAFA',
		followUsAddPacipesHover: '#8BAA36',
		colorTextTeam: '#FAFAFA',

		darkBG: '#2a2c36',
		lightBG: '#1E1F28',
		BGCintoButton: '#FFFFF',
		borderColorLight: '#f0f0f0',
		textSecondary: 'rgba(250, 250, 250, 0.6)',
		addRecipeFormPlaceholder: 'rgba(0, 0, 0, 0.5)',
		addRecipeFormFieldsBackground: 'transparent',
		addRecipeFormFieldsBorder: '1px solid rgba(250, 250, 250, 0.2)',
		colorInput: '#ffffff',

		placeHolderColor: '#FAFAFA',
		borderColor: '#FAFAFA',
		bgColorListSelectIngredient: '#8BAA36',

		addRecipeFormFieldsTextColor: '#23262a',
		addRecipeFormFieldsDropdownBackground: '#ffffff',
		addRecipeFormFieldsDropdownButtonIcon: '#ffffff',
		addRecipeDropDownBg: '#8BAA36',

		addRecipeFormFieldsDropdownListPosition: 'rgba(0, 0, 0, 0.5)',
		addRecipeFormFieldsDropdownListHover: '#22252A',
		addRecipeFormFieldsDeleteButton: '#8BAA36',
		addRecipeFormFieldsDelBtnHover: '#ffffff',

		addRecipeFormCounterButtons: '#FAFAFA',
		colorCounter: '#FAFAFA',
		fontColorNameUser: '#808080',

		followUsHoverAddRecipePage: '#8BAA36',
		addRecipeFormCounterButtonsHover: '#8baa36',
		searchFormBGbyTitle: '#8BAA36',

		bgTrashIcon: '#1E1F28',
		strokeTrashIcon: '#FAFAFA',
		
		bgFavoriteItem: '#2A2C36',
		colorFavoriteTitle: '#FAFAFA',
		textFavoriteRecipe: '#FAFAFA',

		textNoResultsColor: '#FAFAFA',

		recipeItemBackgroundColor: '#2A2C36',
		recipeTextColor: 'rgba(250, 250, 250, 0.6)',
		deleteIconStroke: '#ffffff',
	},
	media: {
		tablet: '(min-width: 768px)',
		desktop: '(min-width: 1440px)',
	},
};
